### ISSUE TITLE
Castlegates bug almost as autistic as the goy who made the plugin

### ISSUE THREAD

**Issue by githubisrunbyjews** [DevotedMC/CastleGates#22]
Bug report is in this album: http://imgur.com/a/IMM16

PS: I made another report with an account but that got flagged because of the username (which was g@sthek!k3s) and I couldn't see it using a different browser, so if this autism has to go through some approval process and by the time you see this there are 2 different posts, that's the reason why. I just created another disposable in case the first post was eaten by the jewhub jews

**Comment by Aleksey-Terzi** [comment]
I problem is still actual - I would appreciate if you will recreate problem on flat environment, because of provided screenshots are not clear for me.  

> flagged because of the username (which was g@sthek!k3s) 

Nice username, you even don't need password.

> Castlegates bug almost as autistic as the goy who made the plugin

Also I confused.
Your album states "Citadel bug".
So who is "autistic goy" Citadel's creator or CastleGates' creator?
