### ISSUE TITLE
Better messaging on failure

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/CastleGates#8]
From ShadedJon:

> I had a complaint about castlegates!
> There should be better error messages why things fail

**Comment by Aleksey-Terzi** [comment]
Improvements are implemented:

1) "Undraw path is blocked" error now show together with blocking block cords and shown explosion effect in the blocking location.

2) "Bridge/gates is broken" error is shown with cords. Also if broken because of not allowed block - the message tells about this. Explosiogn effect shown in the broken location

3) When player is trying to use gearblock as part of bridge - message now clearly tells about this that not allowed + showing cords and explosion effect

4) Removed confusing error messages when auto-creating-and-linking gearblock by clicking to block by gold ingot

All changes are tested on my local environment.

Also suggestion, probably will be better if I will do all my changes directly to DevotedMC fork?
Would be this ok?

**Comment by ProgrammerDan** [comment]
Sounds great! @ShadedJon Any other requests in terms of messaging?

> do all changes directly to DevotedMC fork

Entirely up to you! You are certainly welcome to do so.

**Comment by Aleksey-Terzi** [comment]
If problem is solved I suggest to close this issue.

**Comment by ProgrammerDan** [comment]
Thank you, forgot to do so previously :)
